# Generated by Django 4.2.13 on 2026-05-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('DIRECTOR', 'Директор'), ('HR_MANAGER', 'HR-менеджер'), ('EMPLOYEE', 'Сотрудник'), ('ADMIN', 'Администратор')], default='EMPLOYEE', max_length=20),
        ),
    ]
