# Generated by Django 4.2.13 on 2026-05-06 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('headcount', 'Численность персонала'), ('turnover', 'Текучесть кадров'), ('avg_salary', 'Средняя зарплата'), ('sick_days', 'Дни на больничном'), ('overtime', 'Сверхурочные часы')], max_length=50)),
                ('period', models.DateField(help_text='Первый день прогнозируемого периода')),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('forecast_value', models.FloatField()),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Прогноз метрики',
                'verbose_name_plural': 'Прогнозы метрик',
                'ordering': ['metric', 'period'],
                'unique_together': {('metric', 'period')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(default=0)),
                ('x_tsne', models.FloatField(default=0.0)),
                ('y_tsne', models.FloatField(default=0.0)),
                ('cluster_label', models.CharField(blank=True, max_length=50)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Кластер сотрудника',
                'verbose_name_plural': 'Кластеры сотрудников',
            },
        ),
        migrations.CreateModel(
            name='AttritionPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(default=0.0, help_text='0.0 – 1.0')),
                ('risk_label', models.CharField(default='low', help_text='low/medium/high', max_length=10)),
                ('top_factors', models.JSONField(default=list, help_text='[{"feature": "...", "value": 0.5}, ...]')),
                ('predicted_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attrition_prediction', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Прогноз увольнения',
                'verbose_name_plural': 'Прогнозы увольнений',
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Аномалия',
                'verbose_name_plural': 'Аномалии',
                'ordering': ['-detected_at'],
            },
        ),
    ]
