# Generated by Django 4.2.13 on 2026-05-07 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0003_remove_satisfaction_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('mandatory', 'Обязательный'), ('development', 'Развивающий'), ('technical', 'Технический')], default='mandatory', max_length=20, verbose_name='Категория')),
                ('duration_hours', models.PositiveIntegerField(default=1, verbose_name='Длительность (часов)')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('archived', 'Архив')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Создан кем')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Назначен'), ('in_progress', 'В процессе'), ('completed', 'Завершён'), ('overdue', 'Просрочен')], default='assigned', max_length=20, verbose_name='Статус')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Прогресс (%)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='training.course', verbose_name='Курс')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Назначение курса',
                'verbose_name_plural': 'Назначения курсов',
                'ordering': ['-assigned_at'],
                'unique_together': {('course', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateField(verbose_name='Дата выдачи')),
                ('certificate_number', models.CharField(max_length=50, unique=True, verbose_name='Номер сертификата')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='training.course', verbose_name='Курс')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issued_at'],
                'unique_together': {('employee', 'course')},
            },
        ),
    ]
