# Generated by Django 4.2.13 on 2026-05-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.JSONField(blank=True, default=list, verbose_name='Уроки'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='completed_lessons',
            field=models.JSONField(blank=True, default=list, verbose_name='Пройденные уроки'),
        ),
    ]
