# Generated by Django 4.2.13 on 2026-05-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='awards_last_year',
            field=models.IntegerField(default=0, help_text='Количество награждений за последний год'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bonus_share',
            field=models.FloatField(default=0.1, help_text='Доля переменной части в доходе (0.0-1.0)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='days_since_last_award',
            field=models.IntegerField(default=365, help_text='Дней с последнего награждения'),
        ),
        migrations.AddField(
            model_name='employee',
            name='has_bonus_program',
            field=models.BooleanField(default=False, help_text='Участие в бонусной программе'),
        ),
    ]
