# Generated by Django 4.2.13 on 2026-05-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_add_reward_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='satisfaction_score',
        ),
    ]
