# Generated by Django 4.2.13 on 2026-05-08

from django.db import migrations
import hrm.encryption


def encrypt_existing_data(apps, schema_editor):
    """
    Шифрует существующие plaintext-значения phone и birth_date после изменения
    типа колонок на TEXT. Использует raw SQL чтобы обойти from_db_value/get_prep_value
    исторических моделей.
    """
    from hrm.encryption import AESEncryption, _ENCRYPTED_PREFIX
    cipher = AESEncryption()

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT id, phone, birth_date FROM employees_employee"
        )
        rows = cursor.fetchall()
        for emp_id, phone, birth_date in rows:
            updates = []
            params = []

            if phone and not str(phone).startswith(_ENCRYPTED_PREFIX):
                updates.append('phone = %s')
                params.append(_ENCRYPTED_PREFIX + cipher.encrypt(str(phone)))

            if birth_date and not str(birth_date).startswith(_ENCRYPTED_PREFIX):
                updates.append('birth_date = %s')
                params.append(_ENCRYPTED_PREFIX + cipher.encrypt(str(birth_date)))

            if updates:
                params.append(emp_id)
                cursor.execute(
                    f"UPDATE employees_employee SET {', '.join(updates)} WHERE id = %s",
                    params,
                )


def decrypt_existing_data(apps, schema_editor):
    """Обратная миграция: расшифровывает данные перед возвратом к исходным типам."""
    from hrm.encryption import AESEncryption, _ENCRYPTED_PREFIX
    cipher = AESEncryption()

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "SELECT id, phone, birth_date FROM employees_employee"
        )
        rows = cursor.fetchall()
        for emp_id, phone, birth_date in rows:
            updates = []
            params = []

            if phone and str(phone).startswith(_ENCRYPTED_PREFIX):
                updates.append('phone = %s')
                params.append(cipher.decrypt(str(phone)[len(_ENCRYPTED_PREFIX):]))

            if birth_date and str(birth_date).startswith(_ENCRYPTED_PREFIX):
                updates.append('birth_date = %s')
                params.append(cipher.decrypt(str(birth_date)[len(_ENCRYPTED_PREFIX):]))

            if updates:
                params.append(emp_id)
                cursor.execute(
                    f"UPDATE employees_employee SET {', '.join(updates)} WHERE id = %s",
                    params,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_remove_performance_score'),
    ]

    operations = [
        # 1. Меняем типы колонок: VARCHAR(20)→TEXT и DATE→TEXT
        #    PostgreSQL автоматически кастует DATE::text → 'YYYY-MM-DD'
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=hrm.encryption.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=hrm.encryption.EncryptedDateField(blank=True, null=True),
        ),
        # 2. Шифруем существующие plaintext-значения
        migrations.RunPython(
            encrypt_existing_data,
            reverse_code=decrypt_existing_data,
        ),
    ]
