# Generated by Django 4.2.13 on 2026-05-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_comment',
            field=models.TextField(blank=True, verbose_name='AI-комментарий'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='AI-оценка'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='extracted_skills',
            field=models.JSONField(blank=True, default=list, verbose_name='Извлечённые навыки'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ml_hiring_probability',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Вероятность найма (ML)'),
        ),
    ]
